sudo: false
language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source -q

script:
  - vendor/bin/phpunit
